apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: kube-credential
data:
  ISSUANCE_SERVICE_URL: "http://issuance-service:3001"
  VERIFICATION_SERVICE_URL: "http://verification-service:3002"
  NODE_ENV: "production"
